<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>SSDP.UPnP.PCL</PackageId>
    <AssemblyName>SSDP.UPnP.PCL</AssemblyName>
    <RootNamespace>SSDP.UPnP.PCL</RootNamespace>
    <Version>7.0.0</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SSDP.UPnP.PCL.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="SimpleHttpListener.Rx" Version="7.0.1" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>

</Project>
